# Generated by Django 4.1.7 on 2023-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_review_neg_alter_review_neu_alter_review_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='summary',
        ),
    ]
