# Generated by Django 4.1.7 on 2023-04-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_generalreviews_userreviews_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalreviews',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='userreviews',
            name='updated',
        ),
        migrations.AddField(
            model_name='generalreviews',
            name='flipkart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreviews',
            name='flipkart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
