# Generated by Django 4.1.7 on 2023-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_generalreviews_img_userreviews_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreviews',
            name='sc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalreviews',
            name='sc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalreviews',
            name='sc_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalreviews',
            name='sc_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalreviews',
            name='sc_5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
